services:
  postgresql:
    image: postgres
    container_name: docker-network
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=network
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-network
    ports:
      - '6379:6379'
  
  rabbitmq:
    image: rabbitmq:management  
    container_name: rabbitmq-network
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
    
